def foo(n):
i = 0
sum = 0
while i < n:
sum += 1
i += 1
return sum

foo(n=10)
Этот код вызывает бесконечный цикл, так как не существует условия для остановки цикла. В данном случае, условие i < n всегда истинно, поскольку i увеличивается (i += 1) без ограничения. Это приведет к тому, что функция foo никогда не вернется, застряв в бесконечном цикле.